trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'Azure-For-Students-Connection'
  resourceGroup: 'devops-infra-rg'
  aksCluster: 'aks-devops-cluster'
  namespace: 'default'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Obteniendo credenciales del AKS..."
      az aks get-credentials --resource-group $(resourceGroup) --name $(aksCluster) --overwrite-existing
      
      echo "Aplicando manifiestos de Kubernetes (recursivo)..."
      kubectl apply -R -f manifests/
  displayName: 'Desplegar en AKS'
