trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform-vars

steps:
- checkout: self

# Paso de Autenticación en Azure con AzureCLI@2
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-For-Students-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Autenticado en Azure"
      # Extraer el Tenant ID, Client ID y Subscription ID de la autenticación actual
      echo "##vso[task.setvariable variable=ARM_TENANT_ID;isOutput=false]$(az account show --query tenantId -o tsv)"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;isOutput=false]$(az account show --query id -o tsv)"
  displayName: "Autenticación en Azure"

# Instalar Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'
  displayName: "Instalar Terraform"

# Generar el archivo terraform.tfvars
- script: |
    echo "subscription_id = \"$(ARM_SUBSCRIPTION_ID)\"" > terraform.tfvars
  displayName: "Generar terraform.tfvars"

# Inicializar Terraform con backend remoto
- script: |
    terraform init \
      -backend-config="resource_group_name=terraform-state-rg" \
      -backend-config="storage_account_name=$(tfstate)" \
      -backend-config="container_name=tfstate" \
      -backend-config="key=aks-acr-infra.tfstate"
  displayName: "Terraform Init con backend remoto"
  env:
    ARM_CLIENT_ID: $(client_id)  # Ahora usa el client_id directamente
    ARM_CLIENT_SECRET: $(client_secret)  # Usa el client_secret configurado
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# Ejecutar Terraform Plan
- script: |
    terraform plan -out=tfplan
  displayName: "Terraform Plan"
  env:
    ARM_CLIENT_ID: $(client_id)  # Usa el client_id directamente
    ARM_CLIENT_SECRET: $(client_secret)  # Usa el client_secret configurado
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

# Ejecutar Terraform Apply
- script: |
    terraform apply -auto-approve tfplan
  displayName: "Terraform Apply"
  env:
    ARM_CLIENT_ID: $(client_id)  # Usa el client_id directamente
    ARM_CLIENT_SECRET: $(client_secret)  # Usa el client_secret configurado
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
