trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: terraform-vars

steps:
- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure-For-Students-Connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Autenticado en Azure"

      # Configurar las variables de entorno para Terraform (para que estén disponibles en pasos posteriores)
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID;isOutput=false]$(client_id)"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;isOutput=false]$(client_secret)"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID;isOutput=false]$(subscription_id)"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID;isOutput=false]$(tenant_id)"
  displayName: "Autenticación en Azure"

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.6'
  displayName: "Instalar Terraform"

- script: |
    echo "subscription_id = \"$(ARM_SUBSCRIPTION_ID)\"" > terraform.tfvars
  displayName: "Generar terraform.tfvars"

- script: |
    terraform init \
      -backend-config="resource_group_name=terraform-state-rg" \
      -backend-config="storage_account_name=$(tfstate)" \
      -backend-config="container_name=tfstate" \
      -backend-config="key=aks-acr-infra.tfstate"
  displayName: "Terraform Init con backend remoto"
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

- script: |
    terraform plan -out=tfplan
  displayName: "Terraform Plan"
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)

- script: |
    terraform apply -auto-approve tfplan
  displayName: "Terraform Apply"
  env:
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
